# Generated by Django 2.2.6 on 2019-11-03 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('isAdmin', models.BooleanField()),
                ('dataCriada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='postagem',
            name='numeroComentarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postagem',
            name='numeroCurtidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pontuacao',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Usuario'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Usuario'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='dataCriada',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Usuario')),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Postagem')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Usuario')),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Postagem')),
            ],
        ),
    ]
